#!/usr/bin/env python3
"""Where a project's data lives — decided before the stack is wired, recorded, and checked.

    data_residency.py decide <root> --eu-subjects yes|no --categories identity,tax,... \
                                    --residency-obligations yes|no --avoid-cloud-act yes|no \
                                    [--residency eu|eu-sovereign|none]
    data_residency.py add    <root> --name Neon --service "Postgres database" --data "accounts, bookings" \
                                    --region aws-eu-central-1 --transfer none|dpf|scc|adequacy|... \
                                    [--dpa URL] [--eu-alternative "Scaleway Managed PostgreSQL"] [--by module-add]
    data_residency.py check  <root> [--json]
    data_residency.py render <root>

The decision lives in meta.json (`stack.data_residency`, `compliance.data_categories`, the four answers in
`stack_config.data_residency_answers`). The register lives in `meta.json#compliance.sub_processors` and is
rendered to `docs/compliance/subprocessors.md` — the customer-facing list compliance-audit already owns.

Nothing here blocks a provider. A service with no EU region, or a US-controlled vendor under
"eu-sovereign", is FLAGGED — written into the register with its transfer basis and shown by `check` —
and the work goes on. The only thing update_meta.py's gate refuses is an undecided residency.

Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

RESIDENCY = ("eu", "eu-sovereign", "none")
CATEGORIES = ("identity-documents", "tax", "health", "biometric", "minors", "financial", "location",
              "criminal", "special-category-other", "contact", "usage")
SPECIAL = {"identity-documents", "tax", "health", "biometric", "minors", "financial", "criminal",
           "special-category-other"}
TRANSFER = ("none", "adequacy", "dpf", "scc", "bcr", "derogation", "unknown")
REGISTER_MD = "docs/compliance/subprocessors.md"
MARK = ("<!-- BEGIN:sub-processors (generated by dev-flow/scripts/data_residency.py) -->",
        "<!-- END:sub-processors -->")

# A region string counts as EU when it names an EU/EEA location. Kept as patterns, not a closed list,
# because every provider spells regions differently; see references/eu-data-sovereignty.md for the
# per-provider ids this was written against. UK and Switzerland are adequacy countries, not EU.
EU_REGION = re.compile(
    r"(^|[^a-z])(eu|europe|emea)([-_ ]|$)|\b(fra\d?|cdg\d?|dub\d?|arn\d?|ams\d?|par\d?|waw\d?|mad\d?|mil\d?|fsn\d?|nbg\d?|hel\d?)\b|"
    r"frankfurt|paris|dublin|stockholm|amsterdam|milan|milano|madrid|warsaw|helsinki|vienna|brussels|"
    r"\b(fr|nl|pl|de|it|es|fi|ie|se|at|be)-[a-z]{3}\b|gravelines|roubaix|strasbourg|falkenstein|nuremberg|nuernberg",
    re.I)
ADEQUACY_REGION = re.compile(r"\b(lhr\d?|london|uk|gb|zurich|zrh\d?|geneva|ch)\b|eu-west-2|europe-west2|europe-west6", re.I)

# Services a declared stack implies, so `check` can say which rows the register is missing.
IMPLIED = {
    ("deploy", "vercel"): "Vercel",
    ("db", "neon-drizzle"): "Neon",
    ("db", "supabase"): "Supabase",
    ("auth", "supabase"): "Supabase",
    ("auth", "supabase-auth"): "Supabase",
    ("db", "firebase"): "Firebase",
    ("auth", "firebase"): "Firebase",
    ("auth", "clerk"): "Clerk",
    ("payments", "stripe"): "Stripe",
    ("payments", "revenuecat"): "RevenueCat",
    ("payments", "lemon-squeezy"): "Lemon Squeezy",
    ("storage", "vercel-blob"): "Vercel",
    ("storage", "uploadthing"): "UploadThing",
    ("cms", "sanity"): "Sanity",
    ("deploy", "eas"): "Expo",
    ("push", "expo-notifications"): "Expo",
    ("agent", "eve"): "Vercel",
}


def now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def meta_path(root: Path) -> Path:
    return root / ".workflow" / "meta.json"


def load(root: Path) -> dict:
    p = meta_path(root)
    if not p.exists():
        raise SystemExit(f"no {p} — run dev-flow/scripts/init_workflow.py first")
    return json.loads(p.read_text())


def save(root: Path, meta: dict) -> None:
    meta["updated_at"] = now()
    meta_path(root).write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n")


def region_class(region: str) -> str:
    r = (region or "").strip()
    if not r or r.lower() in {"unknown", "not set", "default"}:
        return "unknown"
    if r.lower() in {"global", "worldwide", "multi-region"}:
        return "global"
    if ADEQUACY_REGION.search(r):
        return "adequacy"
    if EU_REGION.search(r):
        return "eu"
    return "non-eu"


# ---------------------------------------------------------------------------------------------
# decide


def suggest(eu_subjects: bool, categories: list[str], obligations: bool, cloud_act: bool) -> str:
    if not eu_subjects:
        return "none"
    if cloud_act or obligations:
        return "eu-sovereign"
    return "eu"


def cmd_decide(a) -> int:
    root = a.root.resolve()
    meta = load(root)
    yes = lambda v: v == "yes"  # noqa: E731
    cats = [c.strip() for c in (a.categories or "").split(",") if c.strip()]
    unknown = [c for c in cats if c not in CATEGORIES]
    if unknown:
        print(f"unknown categories: {', '.join(unknown)} — use: {', '.join(CATEGORIES)}", file=sys.stderr)
        return 1
    suggested = suggest(yes(a.eu_subjects), cats, yes(a.residency_obligations), yes(a.avoid_cloud_act))
    residency = a.residency or suggested
    meta.setdefault("stack", {})["data_residency"] = residency
    meta.setdefault("compliance", {})["data_categories"] = cats
    meta.setdefault("stack_config", {})["data_residency_answers"] = {
        "eu_subjects": yes(a.eu_subjects), "special_categories": sorted(set(cats) & SPECIAL),
        "residency_obligations": yes(a.residency_obligations), "avoid_cloud_act": yes(a.avoid_cloud_act),
        "suggested": suggested, "decided_at": now(),
    }
    if residency != suggested:
        meta["stack_config"]["data_residency_answers"]["override_reason"] = a.reason or ""
        if not a.reason:
            print(f"note: the answers suggest {suggested!r}; you chose {residency!r} — pass --reason to record why")
    save(root, meta)
    render(root, meta)
    print(f"stack.data_residency = {residency!r} (suggested {suggested!r}) · data_categories = {cats or '[]'}")
    if SPECIAL & set(cats):
        print("special or sensitive categories present: compliance-audit R9 applies, and a DPIA is likely (GDPR Art. 35)")
    return 0


# ---------------------------------------------------------------------------------------------
# register


def cmd_add(a) -> int:
    root = a.root.resolve()
    meta = load(root)
    reg = meta.setdefault("compliance", {}).setdefault("sub_processors", [])
    residency = (meta.get("stack") or {}).get("data_residency")
    rc = region_class(a.region)
    flags = []
    if residency in ("eu", "eu-sovereign") and rc in ("non-eu", "global", "unknown"):
        flags.append(f"region {a.region or 'not set'} is not in the EU")
        if a.transfer in ("none", "unknown"):
            flags.append("no transfer basis recorded (adequacy / DPF / SCC)")
    if residency == "eu-sovereign" and a.us_controlled:
        flags.append("US-controlled vendor under eu-sovereign (CLOUD Act exposure regardless of region)")
    if a.eu_alternative is None and flags:
        flags.append("no EU alternative recorded")
    row = {"name": a.name, "service": a.service, "data": a.data, "region": a.region or "not set",
           "region_class": rc, "transfer": a.transfer, "dpa": a.dpa or "", "us_controlled": bool(a.us_controlled),
           "eu_alternative": a.eu_alternative or "", "flags": flags, "added_by": a.by, "updated_at": now()}
    reg[:] = [r for r in reg if not (r["name"] == a.name and r["service"] == a.service)] + [row]
    save(root, meta)
    render(root, meta)
    print(f"register: {a.name} · {a.service} · {row['region']} ({rc})")
    for f in flags:
        print(f"  ⚠ {f} — flagged, not blocked")
    return 0


def render(root: Path, meta: dict) -> None:
    reg = (meta.get("compliance") or {}).get("sub_processors") or []
    residency = (meta.get("stack") or {}).get("data_residency")
    lines = [MARK[0],
             f"_Data residency: **{residency or 'undecided'}** · categories: "
             f"{', '.join((meta.get('compliance') or {}).get('data_categories') or []) or 'none recorded'} · "
             f"generated {now()[:10]}_", "",
             "| Sub-processor | Service | Personal data | Region | Transfer basis | DPA | Flags |",
             "|---|---|---|---|---|---|---|"]
    for r in sorted(reg, key=lambda r: (r["name"], r["service"])):
        flags = "; ".join(r["flags"]) + (f" — EU alternative: {r['eu_alternative']}" if r.get("eu_alternative") and r["flags"] else "")
        lines.append(f"| {r['name']} | {r['service']} | {r['data']} | {r['region']} | {r['transfer']} | "
                     f"{r['dpa'] or 'TODO'} | {flags or '—'} |")
    lines.append(MARK[1])
    block = "\n".join(lines) + "\n"
    p = root / REGISTER_MD
    p.parent.mkdir(parents=True, exist_ok=True)
    head = ("# Sub-processors\n\n> Not legal advice. A DPO or counsel confirms each DPA and transfer basis.\n\n"
            "Every service that receives personal data on the product's behalf. `module-add` and "
            "`rn-module-add` add a row when they wire a provider; `compliance-audit` verifies it.\n\n")
    text = p.read_text() if p.exists() else head
    if MARK[0] in text:
        text = re.sub(re.escape(MARK[0]) + r".*?" + re.escape(MARK[1]) + r"\n?", block, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n" + block
    p.write_text(text)


# ---------------------------------------------------------------------------------------------
# check


def config_regions(root: Path) -> list[tuple[str, str]]:
    """(where, region) pairs the code itself declares."""
    found = []
    for vj in [root / "vercel.json", *root.glob("apps/*/vercel.json")]:
        if vj.exists():
            try:
                d = json.loads(vj.read_text())
            except json.JSONDecodeError:
                continue
            for r in d.get("regions") or []:
                found.append((str(vj.relative_to(root)), r))
            for fn, cfg in (d.get("functions") or {}).items():
                for r in (cfg or {}).get("regions") or []:
                    found.append((f"{vj.relative_to(root)} functions[{fn}]", r))
    for env in [*root.glob(".env*.example"), *root.glob("apps/*/.env*.example"), *root.glob(".env.example")]:
        for line in env.read_text(errors="ignore").splitlines():
            m = re.match(r"\s*([A-Z0-9_]*(DATABASE_URL|POSTGRES_URL|REGION)[A-Z0-9_]*)\s*=\s*(.+)", line)
            if not m:
                continue
            value = m.group(3).strip().strip('"')
            host = re.search(r"@([^/:?]+)", value)
            region = re.search(r"((?:aws|gcp|azure)-)?[a-z]{2,}-[a-z]+-\d|fra1|cdg1|dub1|arn1|iad1|sfo1", host.group(1) if host else value)
            if region:
                found.append((f"{env.relative_to(root)} {m.group(1)}", region.group(0)))
    return found


def check(root: Path) -> dict:
    meta = load(root)
    stack = meta.get("stack") or {}
    residency = stack.get("data_residency")
    reg = (meta.get("compliance") or {}).get("sub_processors") or []
    out = {"residency": residency, "decided": residency in RESIDENCY, "warnings": [], "flags": []}
    if residency not in RESIDENCY:
        out["warnings"].append("stack.data_residency is undecided — answer the four questions (data_residency.py decide)")
        return out
    names = {r["name"] for r in reg}
    for (key, value), provider in IMPLIED.items():
        if stack.get(key) == value and provider not in names:
            out["warnings"].append(f"stack.{key} = {value!r} implies {provider}, which is not in the register")
    for r in reg:
        for f in r.get("flags") or []:
            out["flags"].append(f"{r['name']} ({r['service']}): {f}")
    if residency != "none":
        for where, region in config_regions(root):
            rc = region_class(region)
            if rc not in ("eu",):
                out["warnings"].append(f"{where} sets region {region} ({rc}) under data_residency={residency}")
    if not (root / REGISTER_MD).exists():
        out["warnings"].append(f"{REGISTER_MD} is missing — run data_residency.py render")
    return out


def cmd_check(a) -> int:
    res = check(a.root.resolve())
    if a.json:
        print(json.dumps(res, indent=2))
    else:
        print(f"data residency: {res['residency'] or 'undecided'}")
        for w in res["warnings"]:
            print(f"  ⚠ {w}")
        for f in res["flags"]:
            print(f"  ⚑ {f}")
        if not res["warnings"] and not res["flags"]:
            print("  ✓ register and config consistent with the decision")
    # warnings and flags inform; only an undecided residency is a failure
    return 0 if res["decided"] else 1


def cmd_render(a) -> int:
    root = a.root.resolve()
    render(root, load(root))
    print(f"rendered {REGISTER_MD}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("decide"); s.add_argument("root", type=Path)
    for flag in ("--eu-subjects", "--residency-obligations", "--avoid-cloud-act"):
        s.add_argument(flag, choices=["yes", "no"], required=True)
    s.add_argument("--categories", default="")
    s.add_argument("--residency", choices=RESIDENCY)
    s.add_argument("--reason")
    s = sub.add_parser("add"); s.add_argument("root", type=Path)
    for flag in ("--name", "--service", "--data"):
        s.add_argument(flag, required=True)
    s.add_argument("--region", default="")
    s.add_argument("--transfer", choices=TRANSFER, default="unknown")
    s.add_argument("--dpa"); s.add_argument("--eu-alternative"); s.add_argument("--by", default="manual")
    s.add_argument("--us-controlled", action="store_true")
    s = sub.add_parser("check"); s.add_argument("root", type=Path); s.add_argument("--json", action="store_true")
    s = sub.add_parser("render"); s.add_argument("root", type=Path)
    a = ap.parse_args(argv)
    return {"decide": cmd_decide, "add": cmd_add, "check": cmd_check, "render": cmd_render}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
