"use client";

/**
 * Root error boundary for the App Router. Triggered by any uncaught error in
 * a server component or server action that bubbles up.
 *
 * Generated by `design-md-to-app`. Customize freely — but keep these rules:
 *  - DO NOT show `error.message` to the user verbatim. It can leak internals.
 *  - DO log to a structured logger (Sentry / Axiom / Datadog) when wired.
 *  - DO offer "retry" via the `reset()` callback that Next provides.
 */
export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  // TODO: replace console.error with structured logger when `module-add observability` lands.
  if (typeof window !== "undefined") {
    console.error("[error.tsx]", error);
  }

  return (
    <div className="min-h-[60vh] flex items-center justify-center px-6 py-16">
      <div className="max-w-md text-center space-y-4">
        <p className="text-[12px] font-bold uppercase tracking-[0.06em] text-on-surface-variant">
          Something went wrong
        </p>
        <h1
          style={{
            fontSize: "clamp(28px, 4vw, 48px)",
            fontWeight: 600,
            lineHeight: 1.1,
            letterSpacing: "-0.01em",
          }}
        >
          We couldn&apos;t load this page.
        </h1>
        <p className="text-[16px] text-on-surface-variant leading-relaxed">
          The error has been recorded. You can try again, or go back to the
          dashboard.
        </p>
        {error.digest ? (
          <p className="text-[12px] font-mono text-on-surface-variant pt-2">
            ref: {error.digest}
          </p>
        ) : null}
        <div className="pt-4 flex gap-3 justify-center">
          <button
            onClick={reset}
            className="inline-flex items-center justify-center rounded-full bg-primary text-on-primary px-6 h-11 text-[14px] font-semibold hover:scale-[1.05] active:scale-[0.95] transition-transform"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-full border border-on-surface/15 px-6 h-11 text-[14px] font-semibold text-on-surface hover:bg-hover transition-colors"
          >
            Back to home
          </a>
        </div>
      </div>
    </div>
  );
}
