/**
 * Default loading skeleton for the App Router. Triggered automatically by
 * Suspense boundaries while the route's RSC is fetching data.
 *
 * Generated by `design-md-to-app`. Customize per-route by adding a
 * `loading.tsx` at the route level (e.g., `app/dashboard/loading.tsx`).
 *
 * Uses shadcn's `<Skeleton>` primitive (installed by `add --all`).
 */
import { Skeleton } from "@/components/ui/skeleton";

export default function Loading() {
  return (
    <div className="px-6 lg:px-12 py-10 space-y-6">
      <div className="space-y-3">
        <Skeleton className="h-4 w-32" />
        <Skeleton className="h-10 w-3/4 max-w-2xl" />
        <Skeleton className="h-4 w-2/3 max-w-xl" />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pt-6">
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="space-y-3">
            <Skeleton className="h-32 w-full rounded-xl" />
            <Skeleton className="h-4 w-3/4" />
            <Skeleton className="h-4 w-1/2" />
          </div>
        ))}
      </div>
    </div>
  );
}
