import type { NextConfig } from "next";

/**
 * Next.js config with security defaults for production.
 *
 * Generated by `design-md-to-app`. The CSP below is intentionally
 * permissive to allow shadcn + Next dev tooling — tighten before prod
 * by removing `'unsafe-inline'` (after styling everything via classes
 * not inline `style=`) and `'unsafe-eval'` (after auditing dependencies).
 */
const securityHeaders = [
  // Prevent the page being framed by other origins (clickjacking).
  { key: "X-Frame-Options", value: "DENY" },
  // Disallow MIME-sniffing — browsers must respect the declared Content-Type.
  { key: "X-Content-Type-Options", value: "nosniff" },
  // Limit how much referrer info is sent on cross-origin requests.
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  // Disable powerful features by default (camera, mic, geolocation, etc.).
  // Re-enable per-feature when you actually need them.
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  },
  // HSTS — enforce HTTPS for 2 years on all subdomains. Only safe AFTER
  // you've fully migrated to HTTPS in prod.
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains; preload",
  },
  // CSP — adjust per app. The default below is a balanced starting point
  // that allows Next/shadcn/Tailwind. Add specific origins as needed.
  {
    key: "Content-Security-Policy",
    value: [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval'", // Next dev needs these; tighten in prod
      "style-src 'self' 'unsafe-inline' fonts.googleapis.com",
      "img-src 'self' data: blob: https:",
      "font-src 'self' fonts.gstatic.com",
      "connect-src 'self' https:",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join("; "),
  },
];

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: securityHeaders,
      },
    ];
  },
  // Optional: opt-in to strict server-action origin checking.
  experimental: {
    serverActions: {
      // Restrict server actions to your own origin(s) only.
      allowedOrigins: ["localhost:3000"],
    },
  },
};

export default nextConfig;
