import Link from "next/link";

/**
 * Brand-iconic footer used on showcase / marketing-style pages.
 * The wordmark is a giant ALL-LOWERCASE rendition of the project slug,
 * sized to span the full container width on desktop. The pattern comes
 * from the design-md-to-app showcase reference (airbnb-clone, aetherfield):
 * a wordmark big enough to BE the footer, surrounded by minimal meta lines.
 */
export function WordmarkFooter() {
  return (
    <footer className="bg-background-primary text-primary border-t border-outline">
      <div className="mx-auto max-w-[1280px] px-6 lg:px-12 pt-16 pb-10 space-y-10">
        {/* Meta row */}
        <div className="flex flex-wrap items-start justify-between gap-6 text-[14px]">
          <div className="space-y-1">
            <div className="text-[11px] font-semibold tracking-[0.32px] uppercase text-on-surface-variant">
              Notarius
            </div>
            <p className="text-on-surface max-w-md">
              CRM moderno per studi notarili italiani. Anagrafica clienti, pratiche,
              scadenze e archivio documentale — in un'unica vista.
            </p>
          </div>
          <div className="flex flex-wrap gap-x-10 gap-y-3 text-[13px] text-on-surface-variant">
            <div className="space-y-2">
              <div className="text-[11px] font-semibold tracking-[0.32px] uppercase">
                Prodotto
              </div>
              <Link href="/" className="block hover:text-primary">
                Dashboard
              </Link>
              <Link href="/pratiche" className="block hover:text-primary">
                Pratiche
              </Link>
              <Link href="/clienti" className="block hover:text-primary">
                Clienti
              </Link>
            </div>
            <div className="space-y-2">
              <div className="text-[11px] font-semibold tracking-[0.32px] uppercase">
                Risorse
              </div>
              <Link href="/showcase" className="block hover:text-primary">
                Design system
              </Link>
              <Link href="/sign-in" className="block hover:text-primary">
                Accedi
              </Link>
              <a href="#" className="block hover:text-primary">
                GDPR · Segreto professionale
              </a>
            </div>
          </div>
        </div>

        {/* Wordmark — sized to span the full container width */}
        <div className="overflow-hidden">
          <div
            className="font-semibold text-primary leading-[0.85] tracking-[-0.04em] select-none"
            style={{
              fontSize: "clamp(96px, 18vw, 240px)",
            }}
          >
            notarius
          </div>
        </div>

        {/* Mono micro-row */}
        <div className="flex flex-wrap items-center justify-between gap-3 pt-6 border-t border-primary/20 font-mono text-[11px] tracking-wide uppercase text-on-surface-variant">
          <div>© 2026 Notarius CRM · Hosted in EU · GDPR-ready</div>
          <div>Generated by design-md-to-app from .workflow/DESIGN.md</div>
        </div>
      </div>
    </footer>
  );
}
